version: '3'
services: 
  app:
    build:
      context: .
    ports: 
      - 80:8080
    depends_on: 
      - db
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
