version: '3'
services: 
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: 
      - "./src/resources/sql/:/docker-entrypoint-initdb.d/"
  app:
    build:
      context: .
    ports: 
      - 80:8080
    depends_on: 
      - db
